version: "3.9"

services:
  # backend:
  #   restart: unless-stopped
  #   build:
  #     context: ./backend
  #     dockerfile: ./docker/production/express/Dockerfile
  #   environment:
  #     - NODE_ENV=production
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "1997"
  #   networks:
  #     - reverseproxy_nw
  
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/production/Dockerfile
#     networks:
#       - reverseproxy_nw

# networks:
#   reverseproxy_nw:
#     external: true